backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

site_url: https://jeangoes.netlify.app/
logo_url: "../assets/img/logo-jean-rgb.svg"

# publish_mode: editorial_workflow
media_folder: static/assets/img
public_folder: /assets/img

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Páginas"
    files:
      - file: "content/_index.md"
        label: "Início"
        name: "inicio"
        fields:
          - {label: Logo, name: image, widget: image, default: "assets/img/jeangoes-logo.svg"}
          - {label: "Link do Vídeo de Início", name: "linkVimeo", widget: string}
          - {label: "Perfil do Vimeo", name: perfilVimeo, widget: object, fields: [
              {label: "Contato Vimeo", name: "linkVimeoContact", widget: string},
              {label: "Visualizar", name: "viewVimeo", widget: "boolean", default: true}
            ]}