backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

site_url: https://jeangoes.netlify.app/
logo_url: "../assets/img/logo-jean-rgb.svg"

# publish_mode: editorial_workflow
media_folder: assets/img

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Páginas"
    files:
      - file: "content/_index.md"
        label: "Início"
        name: "inicio"
        fields:
          - {label: Logo, name: image, widget: image, default: "assets/img/jeangoes-logo.svg"}
          # - {label: "Link do Youtube", name: "link-youtube", widget: "string"}