backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

locale: 'pt'
site_url: https://jeangoes.netlify.app/
logo_url: "../assets/img/pages/logo-jean-rgb.svg"
display_url: https://jeangoes.netlify.app/

# publish_mode: editorial_workflow
media_folder: static/assets/img
public_folder: /assets/img

collections: # A list of collections the CMS should be able to edit
  - name: "settings"
    label: "Configurações"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "config.yml"
        label: "Configurações do Site"
        name: "config"
        fields:
          - {label: "Configurações", name: "params", widget: hidden, fields: [
              - {label: "Logo", name: logoSite, widget: image},
              - {label: "Favicon do Site", name: favSite, hint: "O Favicon é o ícone que aparece nas barras dos navegadores.", widget: image},
              - {label: "Thumbnail (Retangular)", name: thumbRect, hint: "Deve ter 1200x630 pixels. A thumbnail é a imagem que aparece quando você compartilha o link do seu site.", widget: image},
              - {label: "Thumbnail (Quadrada)", name: thumbQuad, hint: "Deve ter 630x630. Algumas plataformas (como o WhastApp) só reconhecem thumbnails quadradas e por isso é importante upar também a thumb quadrada.", widget: image},
              - {label: "Descrição do Site", hint: "A descrição do site aparece nos links de compartilhados e na pesquisa do Google.", name: "description", widget: "text"},
              - {label: "Perfil do Vimeo", name: "perfilVimeo", widget: object, fields: [
                  {label: "Link", name: "linkVimeoContact", widget: string},
                  {label: "Visualizar", name: "viewVimeo", widget: "boolean"}
                ]},
              - {label: "Perfil do YouTube", name: perfilYoutube, widget: object, fields: [
                  {label: "Link", name: "linkYoutubeContact", widget: string},
                  {label: "Visualizar", name: "viewYoutube", widget: "boolean"}
                ]},
              - {label: "Perfil do Instagram", name: perfilInsta, widget: object, fields: [
                  {label: "Link", name: "linkInstaContact", widget: string},
                  {label: "Visualizar", name: "viewInsta", widget: "boolean"}
                ]},
              - {label: "Link do WhastApp", name: perfilWhats, widget: object, fields: [
                  {label: "Link", name: "linkWhatsContact", widget: string},
                  {label: "Visualizar", name: "viewWhats", widget: "boolean"}
                ]},
              - {label: "Perfil do Linkedin", name: perfilLinkedin, widget: object, fields: [
                 {label: "Link", name: "linkLinkedinContact", widget: string},
                 {label: "Visualizar", name: "viewLinkedin", widget: "boolean"}
                ]},
              - {label: "Perfil do Facebook", name: perfilFace, widget: object, fields: [
                  {label: "Link", name: "linkFaceContact", widget: string},
                  {label: "Visualizar", name: "viewFace", widget: "boolean"}
                ]}
            ]}

  - name: "pages"
    label: "Páginas"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/_index.md"
        label: "Início"
        name: "inicio"
       
        fields:
          - {label: "Link do Vídeo de Início", name: "linkVimeo", widget: string}
  