backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

locale: 'pt'

site_url: https://jeangoes.netlify.app/
logo_url: "../assets/uploads/pages/logo-jean-rgb.svg"
display_url: https://jeangoes.netlify.app/

# publish_mode: editorial_workflow
media_folder: static/assets/uploads
public_folder: /assets/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "settings"
    label: "Configurações Gerais"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "config.yml"
        label: "Configurações"
        name: "config"
        fields:
          - {label: "Configurações Gerais", name: "params", widget: object, fields: [
              {label: "Logo (.svg) ", name: "logoSite", widget: image},
              {
                label: "Favicon do Site (.png) | 256 x 256", 
                name: "favSite", 
                widget: image, 
                hint: "O Favicon é o ícone que aparece na barra dos navegadores."
              },
              {
                label: "Thumbnail Retangular (.jpg ou .png) | 1200 x 630", 
                name: "thumbRect", 
                widget: image, 
                hint: "A thumbnail é a imagem que aparece quando você compartilha o link do seu site."
              },
              {
                label: "Thumbnail Quadrada (.jpg ou .png)  | 630 x 630", 
                name: "thumbQuad", 
                widget: image,
                hint: "Algumas plataformas, como o WhatsApp, só reconhecem thumbnails quadradas e por isso é importante upar também essa versão."
              },
              {
                label: "Descrição do Site", 
                name: "description",  
                widget: "text", 
                hint: "A descrição do site aparece nos links compartilhados e na pesquisa do Google."
              },
              {
                label: "Foto de Perfil (Quadrada)", 
                name: "fotoPerfil", 
                widget: image
              },
              {
                label: "Descrição na Barra de Contato", 
                name: "contactDescription",  
                widget: "string", 
                pattern: ['^.{0,100}$', "O texto só pode ter no máximo 100 caracteres."],
                hint: "Máximo de 100 caracteres."
              },
              {
                label: "Currículo",
                name: "curriculum",
                widget: "file",
                config: ,
                  multiple: false
              },
              {label: "Perfil do Vimeo", name: "perfilVimeo", widget: object, fields: [
                {label: "Link", name: "linkVimeoContact", widget: string},
                {label: "Visualizar", name: "viewVimeo", widget: "boolean"}
              ]},
              {label: "Perfil do YouTube", name: perfilYoutube, widget: object, fields: [
                {label: "Link", name: "linkYoutubeContact", widget: string},
                {label: "Visualizar", name: "viewYoutube", widget: "boolean"}
              ]},
              {label: "Perfil do Instagram", name: perfilInsta, widget: object, fields: [
                {label: "Link", name: "linkInstaContact", widget: string},
                {label: "Visualizar", name: "viewInsta", widget: "boolean"}
              ]},
              {label: "Link do WhastApp", name: perfilWhats, widget: object, fields: [
                {label: "Link", name: "linkWhatsContact", widget: string},
                {label: "Visualizar", name: "viewWhats", widget: "boolean"}
              ]},
              {label: "Perfil do Linkedin", name: perfilLinkedin, widget: object, fields: [
                {label: "Link", name: "linkLinkedinContact", widget: string},
                {label: "Visualizar", name: "viewLinkedin", widget: "boolean"}
              ]},
              {label: "Perfil do Facebook", name: perfilFace, widget: object, fields: [
                {label: "Link", name: "linkFaceContact", widget: string},
                {label: "Visualizar", name: "viewFace", widget: "boolean"}
              ]}
            ]}

  - name: "pages"
    label: "Páginas"
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: "content/_index.md"
        label: "Início"
        name: "inicio"
       
        fields:
          - {
              label: "Link do Vídeo de Início", 
              name: "linkVimeo", 
              widget: string,
              hint: "Colocar só o ID do vídeo no Vimeo. Exemplo: o link do vídeo é 'https://vimeo.com/448393321', o ID que deve ser inserido é: '448393321'. "
            }
  